[package]
name = "rustlib"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
rand = "0.8.4"
rand_pcg = "0.3.1"
crossbeam = "0.8.0"
num_cpus = "1.13.0"
dahl-salso = "0.6.0"
epa = { path = "epa" }
roxido = { path = "roxido" }

